# Generated by Django 3.2.11 on 2022-01-12 02:42

from django.db import migrations, models
import django.db.models.deletion
import stream.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticulosListPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_title', models.CharField(help_text='Sobrescribe el título predeterminado', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticulosDetallePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_title', models.CharField(help_text='Overwrites the default title', max_length=100)),
                ('content', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('titulo', wagtail.core.blocks.CharBlock(help_text='Añade tu titulo', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Añade tu texto aqui', required=True))])), ('full_richtext', stream.blocks.RichTextBlock()), ('simple_richtext', stream.blocks.SimpleRichTextBlock()), ('cards', wagtail.core.blocks.StructBlock([('titulo', wagtail.core.blocks.CharBlock(help_text='Añade tu titulo', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('titulo', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('texto', wagtail.core.blocks.TextBlock(max_length=200, required=True)), ('boton_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('boton_url', wagtail.core.blocks.URLBlock(help_text='link', required=False))])))])), ('cta', wagtail.core.blocks.StructBlock([('titulo', wagtail.core.blocks.CharBlock(max_length=60, required=True)), ('texto', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=True)), ('boton_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('boton_url', wagtail.core.blocks.URLBlock(required=False)), ('boton_texto', wagtail.core.blocks.CharBlock(default='Leer más', max_length=200, required=True))]))], blank=True, null=True)),
                ('articulo_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
