# Generated by Django 3.2.11 on 2022-01-14 04:03

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_blogauthorsorderable'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulosdetallepage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='articulos.ArticulosCategoria'),
        ),
    ]
