# Generated by Django 3.2.11 on 2022-01-12 02:33

from django.db import migrations
import stream.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_flexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('titulo', wagtail.core.blocks.CharBlock(help_text='Añade tu titulo', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Añade tu texto aqui', required=True))])), ('full_richtext', stream.blocks.RichTextBlock()), ('simple_richtext', stream.blocks.SimpleRichTextBlock()), ('cards', wagtail.core.blocks.StructBlock([('titulo', wagtail.core.blocks.CharBlock(help_text='Añade tu titulo', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('titulo', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('texto', wagtail.core.blocks.TextBlock(max_length=200, required=True)), ('boton_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('boton_url', wagtail.core.blocks.URLBlock(help_text='link', required=False))])))]))], blank=True, null=True),
        ),
    ]
